In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('food_atlas_combined.csv')
data.index = data.FIPS
data.drop('FIPS',axis = 1,inplace=True)
data.head()

,State,County,PCT_LACCESS_POP10,PCT_LACCESS_LOWI10,PCT_LACCESS_CHILD10,PCT_LACCESS_SENIORS10,PCT_LACCESS_HHNV10,GROCPTH07,SUPERCPTH07,CONVSPTH07,...,PCT_65OLDER10,PCT_18YOUNGER10,MEDHHINC10,POVRATE10,PERPOV10,CHILDPOVRATE10,PERCHLDPOV10,METRO13,POPLOSS00,PCT_OBESE_ADULTS10
FIPS,,,,,,,,,,,,,,,,,,,,,
1001,AL,Autauga,33.769657,9.793530,8.837112,4.376378,3.284786,0.080266,0.020067,0.742465,...,11.995382,26.777959,53049,11.9,0,17.5,0,1,0,30.5
1003,AL,Baldwin,19.318473,5.460261,4.343199,3.513570,2.147827,0.133090,0.017360,1.093655,...,16.771185,22.987408,47618,13.3,0,20.2,0,1,0,26.6
1005,AL,Barbour,20.840972,11.420316,3.425062,2.805166,4.135869,0.201776,0.000000,0.437181,...,14.236807,21.906982,33074,25.3,1,36.2,1,0,0,37.3
1007,AL,Bibb,4.559753,2.144661,1.087518,0.657008,3.458580,0.325809,0.000000,0.372353,...,12.681650,22.696923,35472,20.9,0,28.6,1,1,0,34.3
1009,AL,Blount,2.700840,1.062468,0.671490,0.340269,3.269380,0.105511,0.017585,0.263778,...,14.722096,24.608353,42906,16.5,0,24.1,0,1,0,30.4

In [3]:
# set a list of features for the model 
X = data.iloc[:,2:]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test = train_test_split(X)

In [6]:
X_train.to_csv('data_train.csv')

In [7]:
X_test.to_csv('data_test.csv')

In [ ]:
---------------------------------------------------------------------------------------------------------------------